{
  "readme": "pymanopt_pymanopt_error_readme_6_only_E4",
  "repo_name": "pymanopt_pymanopt",
  "level": "level1",
  "errors": [
    {
      "error_type": "E4",
      "error_description": "References requirements.txt file that doesn't exist in the repository",
      "correction_candidates": [
        "pip install pymanopt",
        "pip install -e .",
        "python setup.py install",
        "conda install pymanopt"
      ],
      "golden_answer": "pip install pymanopt"
    }
  ]
}