{
  "readme": "fedora-python_portingdb_error_readme_8_only_E4",
  "repo_name": "fedora-python_portingdb",
  "level": "level1",
  "errors": [
    {
      "error_type": "E4",
      "error_description": "Changed elsasite.py to main.py which is incorrect filename",
      "correction_candidates": [
        "python elsasite.py freeze",
        "python app.py freeze",
        "python server.py freeze",
        "python freeze.py"
      ],
      "golden_answer": "python elsasite.py freeze"
    }
  ]
}