{
  "readme": "pgeu_pgeu-system_error_readme_8_only_E4",
  "repo_name": "pgeu_pgeu-system",
  "level": "level1",
  "errors": [
    {
      "error_type": "E4",
      "error_description": "References configuration file at system path '/etc/pgeu/database.conf' that likely doesn't exist",
      "correction_candidates": [
        "Make sure to set your database connection in the settings.py file",
        "Make sure to set your database connection in the local_settings.py file",
        "Make sure to set your database connection in the config/database.py file",
        "Make sure to set your database connection in the .env file"
      ],
      "golden_answer": "Make sure to set your database connection in the settings.py file"
    }
  ]
}